name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3.3.1
        with:
          path: '.yarn/cache'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - uses: 'volta-cli/action@v4'
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install --immutable
      - run: yarn exec nx workspace-lint
        name: Workspace lint
      - run: yarn exec nx format:check
        name: Check format
      - run: yarn exec nx affected --target=lint --parallel=3
        name: Lint
      - name: Run tests
        run: |
          yarn exec nx affected --target=test --parallel=3 -c ci --coverage
          yarn exec nx affected --target=e2e --parallel=3 -c ci
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: yarn exec nx affected --target=build --parallel=3
        name: Build
